# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custId', models.CharField(max_length=3)),
                ('custName', models.CharField(max_length=200)),
                ('custAge', models.CharField(max_length=2)),
            ],
        ),
    ]
